In [1]:
import pandas as pd
from pathlib import Path

# Dossier contenant les fichiers DVF
dvf_dir = Path("C:/Users/AdrienSourdille/Desktop/Saint-Vincent-des-Landes-impact-study/data/raw/DVF")

# Liste tous les fichiers .parquet dans le dossier
files = list(dvf_dir.glob("*.parquet"))

# Charge et concatène tous les fichiers
df = pd.concat([pd.read_parquet(f) for f in files], ignore_index=True)

# Filtre le département 44
df_44 = df[df["code_departement"] == "44"]

In [2]:
pd.set_option("display.max_columns", None)
print(df_44.info())

<class 'pandas.core.frame.DataFrame'>
Index: 899750 entries, 1114389 to 35186358
Data columns (total 40 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   id_mutation                   899750 non-null  object
 1   date_mutation                 899750 non-null  object
 2   numero_disposition            899750 non-null  int64
 3   nature_mutation               899750 non-null  object
 4   valeur_fonciere               890720 non-null  float64
 5   adresse_numero                571359 non-null  float64
 6   adresse_suffixe               35673 non-null   object
 7   adresse_nom_voie              889550 non-null  object
 8   adresse_code_voie             889577 non-null  object
 9   code_postal                   889510 non-null  float64
 10  code_commune                  899750 non-null  object
 11  nom_commune                   899750 non-null  object
 12  code_departement              899750 non-null  object
 13  ancien_code_commune           8836 non-null    float64
 14  ancien_nom_commune            8836 non-null    object
 15  id_parcelle                   899750 non-null  object
 16  ancien_id_parcelle            4006 non-null    object
 17  numero_volume                 2482 non-null    object
 18  lot1_numero                   301079 non-null  object
 19  lot1_surface_carrez           73398 non-null   float64
 20  lot2_numero                   63646 non-null   object
 21  lot2_surface_carrez           20568 non-null   float64
 22  lot3_numero                   11896 non-null   object
 23  lot3_surface_carrez           1940 non-null    float64
 24  lot4_numero                   4197 non-null    object
 25  lot4_surface_carrez           485 non-null     float64
 26  lot5_numero                   2128 non-null    object
 27  lot5_surface_carrez           184 non-null     float64
 28  nombre_lots                   899750 non-null  int64
 29  code_type_local               482846 non-null  float64
 30  type_local                    482846 non-null  object
 31  surface_reelle_bati           323113 non-null  float64
 32  nombre_pieces_principales     482275 non-null  float64
 33  code_nature_culture           593278 non-null  object
 34  nature_culture                593278 non-null  object
 35  code_nature_culture_speciale  10111 non-null   object
 36  nature_culture_speciale       10111 non-null   object
 37  surface_terrain               593275 non-null  float64
 38  longitude                     866529 non-null  float64
 39  latitude                      866529 non-null  float64
dtypes: float64(15), int64(2), object(23)
memory usage: 281.4+ MB
None

In [3]:
display(df_44.head())

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,code_commune,nom_commune,code_departement,ancien_code_commune,ancien_nom_commune,id_parcelle,ancien_id_parcelle,numero_volume,lot1_numero,lot1_surface_carrez,lot2_numero,lot2_surface_carrez,lot3_numero,lot3_surface_carrez,lot4_numero,lot4_surface_carrez,lot5_numero,lot5_surface_carrez,nombre_lots,code_type_local,type_local,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude
1114389,2014-461179,2014-01-08,1,Vente,29000.00,7.0,None,AV BASCHER,0568,44000.0,44109,Nantes,44,NaN,None,44109000ET0296,None,None,None,NaN,None,NaN,None,NaN,NaN,NaN,NaN,NaN,0,3.0,Dépendance,NaN,0.0,S,sols,None,None,26.0,-1.545448,47.221956
1114390,2014-461179,2014-01-08,1,Vente,29000.00,7.0,None,AV BASCHER,0568,44000.0,44109,Nantes,44,NaN,None,44109000ET0296,None,None,None,NaN,None,NaN,None,NaN,NaN,NaN,NaN,NaN,0,3.0,Dépendance,NaN,0.0,S,sols,None,None,26.0,-1.545448,47.221956
1114391,2014-461180,2014-01-09,1,Vente en l'état futur d'achèvement,285000.00,29.0,B,RUE DE LA PELLETERIE,6300,44000.0,44109,Nantes,44,NaN,None,44109000MP0284,None,None,61,NaN,None,NaN,None,NaN,NaN,NaN,NaN,NaN,1,3.0,Dépendance,NaN,0.0,None,None,None,None,NaN,NaN,NaN
1114392,2014-461180,2014-01-09,1,Vente en l'état futur d'achèvement,285000.00,29.0,B,RUE DE LA PELLETERIE,6300,44000.0,44109,Nantes,44,NaN,None,44109000MP0284,None,None,1,NaN,None,NaN,None,NaN,NaN,NaN,NaN,NaN,1,2.0,Appartement,65.0,3.0,None,None,None,None,NaN,NaN,NaN
1114393,2014-461181,2014-01-06,1,Vente en l'état futur d'achèvement,251538.46,NaN,None,None,None,NaN,44109,Nantes,44,NaN,None,44109000WZ0123,None,None,12,NaN,None,NaN,None,NaN,NaN,NaN,NaN,NaN,1,NaN,None,NaN,NaN,None,None,None,None,NaN,-1.533561,47.216841

In [4]:
print(df_44["nature_mutation"].value_counts())

df_vente_44 = df_44[df_44["nature_mutation"] == "Vente"]

nature_mutation
Vente                                 793957
Vente en l'état futur d'achèvement     89525
Echange                                 8651
Vente terrain à bâtir                   5747
Adjudication                            1303
Expropriation                            567
Name: count, dtype: int64

In [5]:
print(df_vente_44["type_local"].value_counts())

df_vente_44_MA = df_vente_44[(df_vente_44["type_local"] == "Maison") | (df_vente_44["type_local"] == "Appartement")]

type_local
Maison                                      177945
Dépendance                                  146500
Appartement                                 111188
Local industriel. commercial ou assimilé     24056
Name: count, dtype: int64

In [6]:
print(df_vente_44_MA.info())
display(df_vente_44_MA)

<class 'pandas.core.frame.DataFrame'>
Index: 289133 entries, 1114399 to 35186306
Data columns (total 40 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   id_mutation                   289133 non-null  object
 1   date_mutation                 289133 non-null  object
 2   numero_disposition            289133 non-null  int64
 3   nature_mutation               289133 non-null  object
 4   valeur_fonciere               288137 non-null  float64
 5   adresse_numero                287457 non-null  float64
 6   adresse_suffixe               17655 non-null   object
 7   adresse_nom_voie              289132 non-null  object
 8   adresse_code_voie             289133 non-null  object
 9   code_postal                   289129 non-null  float64
 10  code_commune                  289133 non-null  object
 11  nom_commune                   289133 non-null  object
 12  code_departement              289133 non-null  object
 13  ancien_code_commune           2272 non-null    float64
 14  ancien_nom_commune            2272 non-null    object
 15  id_parcelle                   289133 non-null  object
 16  ancien_id_parcelle            746 non-null     object
 17  numero_volume                 0 non-null       object
 18  lot1_numero                   103386 non-null  object
 19  lot1_surface_carrez           57798 non-null   float64
 20  lot2_numero                   42483 non-null   object
 21  lot2_surface_carrez           15143 non-null   float64
 22  lot3_numero                   6526 non-null    object
 23  lot3_surface_carrez           1231 non-null    float64
 24  lot4_numero                   1791 non-null    object
 25  lot4_surface_carrez           247 non-null     float64
 26  lot5_numero                   698 non-null     object
 27  lot5_surface_carrez           85 non-null      float64
 28  nombre_lots                   289133 non-null  int64
 29  code_type_local               289133 non-null  float64
 30  type_local                    289133 non-null  object
 31  surface_reelle_bati           289127 non-null  float64
 32  nombre_pieces_principales     289127 non-null  float64
 33  code_nature_culture           183709 non-null  object
 34  nature_culture                183709 non-null  object
 35  code_nature_culture_speciale  634 non-null     object
 36  nature_culture_speciale       634 non-null     object
 37  surface_terrain               183708 non-null  float64
 38  longitude                     281018 non-null  float64
 39  latitude                      281018 non-null  float64
dtypes: float64(15), int64(2), object(23)
memory usage: 90.4+ MB
None

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,code_commune,nom_commune,code_departement,ancien_code_commune,ancien_nom_commune,id_parcelle,ancien_id_parcelle,numero_volume,lot1_numero,lot1_surface_carrez,lot2_numero,lot2_surface_carrez,lot3_numero,lot3_surface_carrez,lot4_numero,lot4_surface_carrez,lot5_numero,lot5_surface_carrez,nombre_lots,code_type_local,type_local,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude
1114399,2014-461184,2014-01-02,1,Vente,194400.0,23.0,None,BD EMILE ROMANET,2794,44100.0,44109,Nantes,44,NaN,None,44109000KS0571,None,None,56,NaN,None,NaN,None,NaN,NaN,NaN,NaN,NaN,1,2.0,Appartement,84.0,4.0,None,None,None,None,NaN,-1.603261,47.209692
1114401,2014-461185,2014-01-02,1,Vente,107000.0,11.0,None,RUE DU DOCTEUR ALFRED CORLAY,0882,44800.0,44162,Saint-Herblain,44,NaN,None,44162000DC0492,None,None,241,45.80,None,NaN,None,NaN,NaN,NaN,NaN,NaN,1,2.0,Appartement,46.0,2.0,None,None,None,None,NaN,-1.644254,47.207462
1114402,2014-461186,2014-01-08,1,Vente,295000.0,13.0,None,RUE DE L ARCHE SECHE,0348,44000.0,44109,Nantes,44,NaN,None,44109000HI0097,None,None,49,NaN,52,89.2,None,NaN,NaN,NaN,NaN,NaN,2,2.0,Appartement,105.0,2.0,None,None,None,None,NaN,-1.558665,47.216404
1114403,2014-461187,2014-01-09,1,Vente,208154.0,38.0,None,RUE DE LA PLANCHE AU GUE,5555,44300.0,44109,Nantes,44,NaN,None,44109000VS0113,None,None,120,103.64,None,NaN,None,NaN,NaN,NaN,NaN,NaN,1,2.0,Appartement,103.0,5.0,None,None,None,None,NaN,-1.519753,47.272364
1114406,2014-461188,2014-01-06,1,Vente,79000.0,8.0,None,RUE DES CARMELITES,1436,44000.0,44109,Nantes,44,NaN,None,44109000EP0183,None,None,110,26.45,None,NaN,None,NaN,NaN,NaN,NaN,NaN,1,2.0,Appartement,25.0,1.0,None,None,None,None,NaN,-1.551322,47.216626
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35186297,2024-556766,2024-12-30,1,Vente,111200.0,38.0,None,AV ALBERT DE MUN,0060,44600.0,44184,Saint-Nazaire,44,NaN,None,44184000VP0115,None,None,8,42.43,None,NaN,None,NaN,None,NaN,NaN,NaN,1,2.0,Appartement,40.0,3.0,None,None,None,None,NaN,-2.209471,47.278543
35186298,2024-556767,2024-12-31,1,Vente,475000.0,3.0,None,RUE DES PAVILLONS (VC42),2540,44490.0,44049,Le Croisic,44,NaN,None,44049000AM0265,None,None,None,NaN,None,NaN,None,NaN,None,NaN,NaN,NaN,0,1.0,Maison,74.0,3.0,S,sols,None,None,105.0,-2.509843,47.291977
35186300,2024-556769,2024-12-30,1,Vente,170000.0,1.0,None,RUE SAINT MICHEL,2180,44350.0,44069,Guérande,44,NaN,None,44069000AK0372,None,None,16,NaN,5,NaN,9,49.35,None,NaN,NaN,NaN,3,2.0,Appartement,48.0,2.0,None,None,None,None,NaN,-2.428762,47.327878
35186304,2024-556771,2024-12-30,1,Vente,107000.0,6.0,None,RUE LOUIS PASTEUR,3920,44600.0,44184,Saint-Nazaire,44,NaN,None,44184000XT0118,None,None,1,69.88,2,NaN,None,NaN,None,NaN,NaN,NaN,2,2.0,Appartement,67.0,4.0,None,None,None,None,NaN,-2.214620,47.272013
35186306,2024-556772,2024-12-30,1,Vente,430000.0,11.0,None,CHE DE LA PAILLERESSE,1057,44380.0,44132,Pornichet,44,NaN,None,44132000BK0054,None,None,None,NaN,None,NaN,None,NaN,None,NaN,NaN,NaN,0,1.0,Maison,172.0,5.0,S,sols,None,None,857.0,-2.314193,47.257276

In [7]:
df_vente_44_MA["price_per_m2"] = df_vente_44_MA["valeur_fonciere"] / df_vente_44_MA["surface_reelle_bati"]

C:\Users\AdrienSourdille\AppData\Local\Temp\ipykernel_48724\3690153739.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_vente_44_MA["price_per_m2"] = df_vente_44_MA["valeur_fonciere"] / df_vente_44_MA["surface_reelle_bati"]

In [8]:
import geopandas as gpd
from shapely.geometry import Point

# Drop rows with missing coordinates
df_clean = df_vente_44_MA.dropna(subset=["longitude", "latitude"])

# Create geometry points
geometry = [Point(xy) for xy in zip(df_clean["longitude"], df_clean["latitude"])]

# Create GeoDataFrame
gdf = gpd.GeoDataFrame(df_clean, geometry=geometry, crs="EPSG:4326")  # WGS84

In [9]:
display(gdf.head())

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,code_commune,nom_commune,code_departement,ancien_code_commune,ancien_nom_commune,id_parcelle,ancien_id_parcelle,numero_volume,lot1_numero,lot1_surface_carrez,lot2_numero,lot2_surface_carrez,lot3_numero,lot3_surface_carrez,lot4_numero,lot4_surface_carrez,lot5_numero,lot5_surface_carrez,nombre_lots,code_type_local,type_local,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude,price_per_m2,geometry
1114399,2014-461184,2014-01-02,1,Vente,194400.0,23.0,None,BD EMILE ROMANET,2794,44100.0,44109,Nantes,44,NaN,None,44109000KS0571,None,None,56,NaN,None,NaN,None,NaN,NaN,NaN,NaN,NaN,1,2.0,Appartement,84.0,4.0,None,None,None,None,NaN,-1.603261,47.209692,2314.285714,POINT (-1.60326 47.20969)
1114401,2014-461185,2014-01-02,1,Vente,107000.0,11.0,None,RUE DU DOCTEUR ALFRED CORLAY,0882,44800.0,44162,Saint-Herblain,44,NaN,None,44162000DC0492,None,None,241,45.80,None,NaN,None,NaN,NaN,NaN,NaN,NaN,1,2.0,Appartement,46.0,2.0,None,None,None,None,NaN,-1.644254,47.207462,2326.086957,POINT (-1.64425 47.20746)
1114402,2014-461186,2014-01-08,1,Vente,295000.0,13.0,None,RUE DE L ARCHE SECHE,0348,44000.0,44109,Nantes,44,NaN,None,44109000HI0097,None,None,49,NaN,52,89.2,None,NaN,NaN,NaN,NaN,NaN,2,2.0,Appartement,105.0,2.0,None,None,None,None,NaN,-1.558665,47.216404,2809.523810,POINT (-1.55866 47.2164)
1114403,2014-461187,2014-01-09,1,Vente,208154.0,38.0,None,RUE DE LA PLANCHE AU GUE,5555,44300.0,44109,Nantes,44,NaN,None,44109000VS0113,None,None,120,103.64,None,NaN,None,NaN,NaN,NaN,NaN,NaN,1,2.0,Appartement,103.0,5.0,None,None,None,None,NaN,-1.519753,47.272364,2020.912621,POINT (-1.51975 47.27236)
1114406,2014-461188,2014-01-06,1,Vente,79000.0,8.0,None,RUE DES CARMELITES,1436,44000.0,44109,Nantes,44,NaN,None,44109000EP0183,None,None,110,26.45,None,NaN,None,NaN,NaN,NaN,NaN,NaN,1,2.0,Appartement,25.0,1.0,None,None,None,None,NaN,-1.551322,47.216626,3160.000000,POINT (-1.55132 47.21663)

In [10]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
from geopy.distance import geodesic


# --- Define coordinates of the wind farm ---
windfarm_coords = (47.6670, -1.3170)  # (latitude, longitude)

# --- Calculate geodesic distance to wind farm (in km) ---
gdf["distance_km"] = gdf.apply(
    lambda row: geodesic((row["latitude"], row["longitude"]), windfarm_coords).km,
    axis=1
)

# --- Drop geometry to reduce size ---
df_final = gdf.drop(columns="geometry")

In [ ]:
import numpy as np

# df.distance_km is your computed distance
bins = [0, 1, 2, 5, 10, 20, 30, np.inf]
labels = ['0-1 km', '1-2 km', '2-5 km', '5-10 km', '10-20 km', '20-30 km', '>30 km']

df['distance_bucket'] = pd.cut(
    df['distance_km'],
    bins=bins,
    labels=labels,
    right=False
)

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,code_commune,nom_commune,code_departement,ancien_code_commune,ancien_nom_commune,id_parcelle,ancien_id_parcelle,numero_volume,lot1_numero,lot1_surface_carrez,lot2_numero,lot2_surface_carrez,lot3_numero,lot3_surface_carrez,lot4_numero,lot4_surface_carrez,lot5_numero,lot5_surface_carrez,nombre_lots,code_type_local,type_local,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude,price_per_m2,distance_km
1114399,2014-461184,2014-01-02,1,Vente,194400.0,23.0,None,BD EMILE ROMANET,2794,44100.0,44109,Nantes,44,NaN,None,44109000KS0571,None,None,56,NaN,None,NaN,None,NaN,NaN,NaN,NaN,NaN,1,2.0,Appartement,84.0,4.0,None,None,None,None,NaN,-1.603261,47.209692,2314.285714,55.238448
1114401,2014-461185,2014-01-02,1,Vente,107000.0,11.0,None,RUE DU DOCTEUR ALFRED CORLAY,0882,44800.0,44162,Saint-Herblain,44,NaN,None,44162000DC0492,None,None,241,45.80,None,NaN,None,NaN,NaN,NaN,NaN,NaN,1,2.0,Appartement,46.0,2.0,None,None,None,None,NaN,-1.644254,47.207462,2326.086957,56.742230
1114402,2014-461186,2014-01-08,1,Vente,295000.0,13.0,None,RUE DE L ARCHE SECHE,0348,44000.0,44109,Nantes,44,NaN,None,44109000HI0097,None,None,49,NaN,52,89.2,None,NaN,NaN,NaN,NaN,NaN,2,2.0,Appartement,105.0,2.0,None,None,None,None,NaN,-1.558665,47.216404,2809.523810,53.310081
1114403,2014-461187,2014-01-09,1,Vente,208154.0,38.0,None,RUE DE LA PLANCHE AU GUE,5555,44300.0,44109,Nantes,44,NaN,None,44109000VS0113,None,None,120,103.64,None,NaN,None,NaN,NaN,NaN,NaN,NaN,1,2.0,Appartement,103.0,5.0,None,None,None,None,NaN,-1.519753,47.272364,2020.912621,46.461764
1114406,2014-461188,2014-01-06,1,Vente,79000.0,8.0,None,RUE DES CARMELITES,1436,44000.0,44109,Nantes,44,NaN,None,44109000EP0183,None,None,110,26.45,None,NaN,None,NaN,NaN,NaN,NaN,NaN,1,2.0,Appartement,25.0,1.0,None,None,None,None,NaN,-1.551322,47.216626,3160.000000,53.099971

In [11]:
# --- Save the result as lightweight CSV ---
output_path = "C:/Users/AdrienSourdille/Desktop/Saint-Vincent-des-Landes-impact-study/data/processed/dvf_vente_44_distances.csv"
df_final.to_csv(output_path, index=False)

print(f"✅ Saved file with distances to: {output_path}")

✅ Saved file with distances to: C:/Users/AdrienSourdille/Desktop/Saint-Vincent-des-Landes-impact-study/data/processed/dvf_vente_44_distances.csv